### ISSUE TITLE
User namespaces

### ISSUE THREAD

**Issue by dalai4git** [lizrice/container-security#10]
It is not always possible to run `unshare --user bash` without sudo. For example in Debian this seems to be not allowed by default: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808915.

**Comment by lizrice** [comment]
This seems like it was a bug in Debian? So I'm not sure it makes sense to refer to it in the book. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780841
